Repository testit-tms/adapters-python, pull requests merged in 2023-05, with the labels that each got.

#72 Fixed creating an attachment without a step.
  testit-python-commons/src/testit_python_commons/dynamic_methods.py
Labels: bug

#73 Fixed using dynamic methods without a step for Behave.
  testit-adapter-behave/setup.py
  testit-adapter-nose/setup.py
  testit-adapter-nose/src/testit_adapter_nose/listener.py
  testit-adapter-pytest/setup.py
  testit-python-commons/setup.py
Labels: bug

#74 Fixed "nameSpace" and "className" tags for RobotFramework.
  testit-adapter-robotframework/src/testit_adapter_robotframework/models.py
Labels: bug

#75 Updated documentation.
  testit-adapter-behave/README.md
  testit-adapter-nose/README.md
  testit-adapter-pytest/README.md
  testit-adapter-robotframework/README.md
Labels: documentation

#76 Added models for python-commons.
  testit-adapter-behave/src/testit_adapter_behave/listener.py
  testit-adapter-behave/src/testit_adapter_behave/utils.py
  testit-adapter-nose/src/testit_adapter_nose/listener.py
  testit-adapter-nose/src/testit_adapter_nose/utils.py
  testit-adapter-pytest/README.md
  testit-adapter-pytest/src/testit_adapter_pytest/listener.py
  testit-adapter-pytest/src/testit_adapter_pytest/utils.py
  testit-adapter-robotframework/src/testit_adapter_robotframework/listeners.py
  testit-adapter-robotframework/src/testit_adapter_robotframework/utils.py
  testit-python-commons/setup.py
  testit-python-commons/src/testit_python_commons/client/api_client.py
  testit-python-commons/src/testit_python_commons/client/converter.py
  testit-python-commons/src/testit_python_commons/decorators.py
  testit-python-commons/src/testit_python_commons/dynamic_methods.py
  testit-python-commons/src/testit_python_commons/models/link.py
  testit-python-commons/src/testit_python_commons/models/step_result.py
  testit-python-commons/src/testit_python_commons/models/test_result.py
  testit-python-commons/src/testit_python_commons/services/adapter_manager.py
  testit-python-commons/src/testit_python_commons/services/utils.py
Labels: enhancement

#77 Used "get_function_parameters" method from Utils in logger.
  testit-python-commons/src/testit_python_commons/services/logger.py
Labels: enhancement

#79 Fixed filtering of tests for RobotFramework.
  testit-adapter-robotframework/src/testit_adapter_robotframework/listeners.py
Labels: bug

#80 Feature/add models to python commons
  testit-adapter-behave/src/testit_adapter_behave/models/url_link.py
  testit-adapter-behave/src/testit_adapter_behave/scenario_parser.py
  testit-adapter-behave/src/testit_adapter_behave/tags_parser.py
  testit-adapter-behave/src/testit_adapter_behave/utils.py
  testit-adapter-nose/src/testit_adapter_nose/utils.py
  testit-adapter-pytest/src/testit_adapter_pytest/listener.py
  testit-adapter-pytest/src/testit_adapter_pytest/utils.py
  testit-adapter-robotframework/src/testit_adapter_robotframework/TMSLibrary.py
  testit-adapter-robotframework/src/testit_adapter_robotframework/models.py
  testit-python-commons/src/testit_python_commons/client/converter.py
  testit-python-commons/src/testit_python_commons/decorators.py
  testit-python-commons/src/testit_python_commons/dynamic_methods.py
  testit-python-commons/src/testit_python_commons/services/logger.py
  testit-python-commons/src/testit_python_commons/services/utils.py
Labels: bug

#81 Update api_client.py
  testit-python-commons/src/testit_python_commons/client/api_client.py
Labels: bug

#88 Fixed linking of autotest to workitem.
  testit-adapter-behave/setup.py
  testit-adapter-nose/setup.py
  testit-adapter-pytest/setup.py
  testit-adapter-robotframework/setup.py
  testit-python-commons/setup.py
  testit-python-commons/src/testit_python_commons/client/api_client.py
Labels: bug
