Repository testit-tms/adapters-python, pull requests merged in 2023-12, with the labels that each got.

#116 Added a metric to the documentation.
  testit-adapter-behave/README.md
  testit-adapter-nose/README.md
  testit-adapter-pytest/README.md
  testit-adapter-robotframework/README.md
Labels: documentation

#115 Fixed getting the link type.
  testit-adapter-behave/setup.py
  testit-adapter-nose/setup.py
  testit-adapter-pytest/setup.py
  testit-adapter-robotframework/setup.py
  testit-python-commons/setup.py
Labels: bug

#117 Updated workflow
  .github/workflows/code_checks.yml
Labels: enhancement

#118 Added attachment binding to the step.
  testit-adapter-behave/setup.py
  testit-adapter-nose/setup.py
  testit-adapter-pytest/setup.py
  testit-adapter-robotframework/setup.py
  testit-adapter-robotframework/src/testit_adapter_robotframework/listeners.py
  testit-adapter-robotframework/src/testit_adapter_robotframework/models.py
  testit-python-commons/setup.py
Labels: enhancement
