Repository testit-tms/adapters-python, pull requests merged in 2023-10, with the labels that each got.

#108 Added loading of fixture steps in the test results.
  testit-adapter-behave/setup.py
  testit-adapter-nose/setup.py
  testit-adapter-pytest/setup.py
  testit-adapter-pytest/src/testit_adapter_pytest/fixture_context.py
  testit-adapter-pytest/src/testit_adapter_pytest/fixture_manager.py
  testit-adapter-pytest/src/testit_adapter_pytest/fixture_storage.py
  testit-adapter-pytest/src/testit_adapter_pytest/listener.py
  testit-adapter-pytest/src/testit_adapter_pytest/models/__init__.py
  testit-adapter-pytest/src/testit_adapter_pytest/models/fixture.py
  testit-adapter-pytest/src/testit_adapter_pytest/utils.py
  testit-adapter-robotframework/setup.py
  testit-python-commons/setup.py
  testit-python-commons/src/testit_python_commons/client/api_client.py
  testit-python-commons/src/testit_python_commons/client/converter.py
  testit-python-commons/src/testit_python_commons/models/test_result_with_all_fixture_step_results_model.py
  testit-python-commons/src/testit_python_commons/services/adapter_manager.py
  testit-python-commons/src/testit_python_commons/services/step_manager.py
  testit-python-commons/src/testit_python_commons/step.py
Labels: enhancement

#109 Added "attrs" to setup.py.
  testit-adapter-behave/setup.py
  testit-adapter-nose/setup.py
  testit-adapter-pytest/setup.py
  testit-adapter-robotframework/setup.py
  testit-python-commons/setup.py
Labels: bug

#110 Fixed updating of test results.
  testit-adapter-behave/setup.py
  testit-adapter-nose/setup.py
  testit-adapter-pytest/setup.py
  testit-adapter-robotframework/setup.py
  testit-python-commons/setup.py
  testit-python-commons/src/testit_python_commons/client/api_client.py
  testit-python-commons/src/testit_python_commons/client/converter.py
  testit-python-commons/src/testit_python_commons/models/test_result_with_all_fixture_step_results_model.py
Labels: bug

#111 Update converter.py
  testit-python-commons/src/testit_python_commons/client/converter.py
Labels: bug

#112 Updated version of packages.
  testit-adapter-behave/setup.py
  testit-adapter-nose/setup.py
  testit-adapter-pytest/setup.py
  testit-adapter-robotframework/setup.py
  testit-python-commons/setup.py
  testit-python-commons/src/testit_python_commons/client/converter.py
Labels: documentation
