Repository testit-tms/adapters-python, pull requests merged in 2023-04, with the labels that each got.

#66 Feature/support decorators for class
  .github/workflows/code_checks.yml
  testit-adapter-behave/setup.py
  testit-adapter-nose/setup.py
  testit-adapter-pytest/setup.py
  testit-adapter-robotframework/setup.py
  testit-python-commons/setup.py
  testit-python-commons/src/testit_python_commons/decorators.py
  testit-python-commons/src/testit_python_commons/services/utils.py
Labels: bug, enhancement

#67 Fixed step parameters for Behave.
  testit-adapter-behave/setup.py
  testit-adapter-behave/src/testit_adapter_behave/listener.py
  testit-adapter-behave/src/testit_adapter_behave/scenario_parser.py
  testit-adapter-nose/setup.py
  testit-adapter-pytest/setup.py
  testit-adapter-robotframework/setup.py
  testit-python-commons/setup.py
  testit-python-commons/src/testit.py
  testit-python-commons/src/testit_python_commons/app_properties.py
  testit-python-commons/src/testit_python_commons/client/converter.py
  testit-python-commons/src/testit_python_commons/decorators.py
  testit-python-commons/src/testit_python_commons/dynamic_methods.py
  testit-python-commons/src/testit_python_commons/services/adapter_manager.py
  testit-python-commons/src/testit_python_commons/services/logger.py
  testit-python-commons/src/testit_python_commons/services/utils.py
  testit-python-commons/src/testit_python_commons/step.py
Labels: bug

#65 Add label verifier
  .github/workflows/code_checks.yml
  .github/workflows/label-verifier.yml
  .github/workflows/python-publish.yml
  requirements.txt
Labels: enhancement

#69 Fixed ExternalId tag for Behave.
  testit-adapter-behave/setup.py
  testit-adapter-behave/src/testit_adapter_behave/scenario_parser.py
  testit-adapter-nose/setup.py
  testit-adapter-pytest/setup.py
  testit-adapter-robotframework/setup.py
  testit-python-commons/setup.py
Labels: bug

#70 Fixed get adapter_manager for RobotFramework.
  testit-adapter-robotframework/src/testit_adapter_robotframework/TMSLibrary.py
Labels: bug

#71 fix publish
  .github/workflows/python-publish.yml
Labels: enhancement
