Repository testit-tms/adapters-python, pull requests merged in 2023-03, with the labels that each got.

#55 Feature/add adapter nose2
  README.md
  testit-adapter-nose/README.md
  testit-adapter-nose/setup.py
  testit-adapter-nose/src/testit_adapter_nose/__init__.py
  testit-adapter-nose/src/testit_adapter_nose/listener.py
  testit-adapter-nose/src/testit_adapter_nose/plugin.py
  testit-adapter-nose/src/testit_adapter_nose/utils.py
Labels: documentation, enhancement

#56 Added automaticCreationTestCases property.
  testit-adapter-behave/README.md
  testit-adapter-behave/setup.py
  testit-adapter-behave/src/testit_adapter_behave/utils.py
  testit-adapter-nose/README.md
  testit-adapter-nose/setup.py
  testit-adapter-pytest/README.md
  testit-adapter-pytest/setup.py
  testit-adapter-pytest/src/testit_adapter_pytest/plugin.py
  testit-adapter-robotframework/README.md
  testit-adapter-robotframework/setup.py
  testit-adapter-robotframework/src/testit_adapter_robotframework/TMSLibrary.py
  testit-adapter-robotframework/src/testit_adapter_robotframework/models.py
  testit-python-commons/setup.py
  testit-python-commons/src/testit_python_commons/app_properties.py
  testit-python-commons/src/testit_python_commons/client/converter.py
  testit-python-commons/src/testit_python_commons/services/adapter_manager.py
  testit-python-commons/src/testit_python_commons/services/adapter_manager_configuration.py
Labels: documentation, enhancement

#58 Hotfix/load nested steps
  testit-adapter-behave/setup.py
  testit-adapter-nose/setup.py
  testit-adapter-pytest/setup.py
  testit-adapter-robotframework/setup.py
  testit-python-commons/setup.py
  testit-python-commons/src/testit_python_commons/client/converter.py
Labels: bug

#59 Fixed github actions.
  testit-python-commons/setup.py
Labels: bug

#62 Relocated compatibility table.
  README.md
  testit-adapter-behave/README.md
  testit-adapter-nose/README.md
  testit-adapter-pytest/README.md
  testit-adapter-robotframework/README.md
Labels: documentation

#47 namespace by decorator
  testit-python-commons/src/testit.py
  testit-python-commons/src/testit_python_commons/decorators.py
  testit-python-commons/src/testit_python_commons/services/utils.py
Labels: enhancement

#64 Fixed duplication of logs.
  testit-python-commons/src/testit_python_commons/client/api_client.py
  testit-python-commons/src/testit_python_commons/client/converter.py
  testit-python-commons/src/testit_python_commons/services/logger.py
  testit-python-commons/src/testit_python_commons/services/utils.py
  testit-python-commons/src/testit_python_commons/step.py
Labels: bug
