Repository testit-tms/adapters-python, pull requests merged in 2025-06, with the labels that each got.

#184 tests: added unit tests for testit-python-commons
  .github/workflows/validate.yml
  README.md
  testit-adapter-behave/pytest.ini
  testit-adapter-behave/tests/test_formatter.py
  testit-adapter-nose/pytest.ini
  testit-adapter-nose/tests/test_plugin.py
  testit-adapter-pytest/pytest.ini
  testit-adapter-pytest/tests/test_listener.py
  testit-adapter-robotframework/pytest.ini
  testit-adapter-robotframework/tests/test_listeners.py
  testit-python-commons/pytest.ini
  testit-python-commons/tests/conftest.py
  testit-python-commons/tests/services/test_adapter_manager.py
  testit-python-commons/tests/services/test_fixture_manager.py
  testit-python-commons/tests/services/test_plugin_manager.py
  testit-python-commons/tests/services/test_step_manager.py
  testit-python-commons/tests/services/test_utils.py
  testit-python-commons/tests/test_app_properties.py
  testit-python-commons/tests/test_dynamic_methods.py
Labels: tests

#186 fix: TMS-30624: support the api-client v6.2 with pydantic v1.
  testit-adapter-behave/setup.py
  testit-adapter-nose/setup.py
  testit-adapter-pytest/setup.py
  testit-adapter-robotframework/setup.py
  testit-python-commons/setup.py
  testit-python-commons/src/testit_python_commons/client/api_client.py
Labels: bug

#187 fix: TMS-33439: fix parsing the pyproject.toml.
  testit-adapter-behave/setup.py
  testit-adapter-nose/setup.py
  testit-adapter-pytest/setup.py
  testit-adapter-robotframework/setup.py
  testit-python-commons/requirements.txt
  testit-python-commons/setup.py
  testit-python-commons/src/testit_python_commons/app_properties.py
Labels: bug

#189 feat: update the package versions for tms 5.3.
  testit-adapter-behave/setup.py
  testit-adapter-nose/setup.py
  testit-adapter-pytest/setup.py
  testit-adapter-robotframework/setup.py
  testit-python-commons/setup.py
Labels: documentation
