Repository testit-tms/adapters-python, pull requests merged in 2025-04, with the labels that each got.

#175 fix: TMS-28555: fix getting annotations for tests in testclasses for …
  testit-adapter-behave/setup.py
  testit-adapter-nose/setup.py
  testit-adapter-nose/src/testit_adapter_nose/utils.py
  testit-adapter-pytest/setup.py
  testit-adapter-robotframework/setup.py
  testit-python-commons/setup.py
Labels: bug

#176 fix: fix renaming the "func" variable for Nose2.
  testit-adapter-behave/setup.py
  testit-adapter-nose/setup.py
  testit-adapter-nose/src/testit_adapter_nose/utils.py
  testit-adapter-pytest/setup.py
  testit-adapter-robotframework/setup.py
  testit-python-commons/setup.py
Labels: bug

#173 fix: Add pyproject.toml handling
  testit-adapter-behave/README.md
  testit-adapter-nose/README.md
  testit-adapter-pytest/README.md
  testit-adapter-robotframework/README.md
  testit-python-commons/src/testit_python_commons/app_properties.py
Labels: documentation, enhancement

#178 Release/3.5.0
  testit-adapter-behave/README.md
  testit-adapter-behave/setup.py
  testit-adapter-nose/README.md
  testit-adapter-nose/setup.py
  testit-adapter-pytest/README.md
  testit-adapter-pytest/setup.py
  testit-adapter-robotframework/README.md
  testit-adapter-robotframework/setup.py
  testit-python-commons/setup.py
  testit-python-commons/src/testit_python_commons/app_properties.py
Labels: documentation, enhancement

#177 feat: support tms 5.3.
  README.md
  testit-adapter-behave/setup.py
  testit-adapter-nose/setup.py
  testit-adapter-pytest/setup.py
  testit-adapter-robotframework/setup.py
  testit-python-commons/setup.py
Labels: documentation

#180 feat: TMS-30718: add dynamic methods for Pytest.
  testit-adapter-behave/setup.py
  testit-adapter-nose/setup.py
  testit-adapter-pytest/README.md
  testit-adapter-pytest/setup.py
  testit-adapter-pytest/src/testit_adapter_pytest/listener.py
  testit-adapter-pytest/src/testit_adapter_pytest/utils.py
  testit-adapter-robotframework/setup.py
  testit-python-commons/setup.py
  testit-python-commons/src/testit.py
  testit-python-commons/src/testit_python_commons/decorators.py
  testit-python-commons/src/testit_python_commons/dynamic_methods.py
Labels: documentation, enhancement

#181 feat: update the package versions for cloud.
  testit-adapter-behave/setup.py
  testit-adapter-nose/setup.py
  testit-adapter-pytest/setup.py
  testit-adapter-robotframework/setup.py
  testit-python-commons/setup.py
Labels: documentation

#182 fix: model issue fix
  README.md
  testit-adapter-behave/setup.py
  testit-adapter-nose/setup.py
  testit-adapter-pytest/setup.py
  testit-adapter-robotframework/setup.py
  testit-python-commons/setup.py
  testit-python-commons/src/testit_python_commons/client/api_client.py
Labels: bug
